apiVersion: v1
kind: Secret
metadata:
  name: site-cert
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
