- name: Create security namespace
  community.kubernetes.k8s:
    name: "{{ namespace }}"
    api_version: v1
    kind: namespace
    state: present
    username: kubernetes-admin

- name: Add Voight.org Certificates
  community.kubernetes.helm:
    name: certificatesbuild
    chart_ref: ./roles/common/files/global
    release_namespace: "{{ namespace }}"
    values:
      namespace: "{{ namespace }}"
      tls.key: "{{ voightorgkey }}"
      tls.crt: "{{ voightorgcrt }}"

#  command: >
#    helm upgrade -i -n "{{ namespace }}" certificates files/global
#    --set namespace="{{ namespace }}"
#    --set-file tls.crt="{{ voightorgcrt }}"
#    --set tls.key='{{ voightorgkey }}'

- name: Add Hashicorp Repo
  community.kubernetes.helm_repository:
    name: hashicorp
    repo_url: "https://helm.releases.hashicorp.com"

- name: Apply Vault
  community.kubernetes.helm:
    name: vaultbuild
    chart_ref: hashicorp/vault
    release_namespace: "{{ namespace }}"
    values_files:
      - ./roles/common/files/vault-values.yaml

#  command: helm upgrade -i -n "{{ namespace }}" vaultbuild hashicorp/vault -f ./vault-values.yaml

- name: Initialize Vault
  command: echo "When the pod comes up, run:\nkubectl exec -it -n security vault-0 -- vault operator init"
