- name: Install Hashicorp Vault
  hosts: localhost
  vars_files:
    - files/admin-values.yaml
  vars:
    namespace: blahblahblah

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create security namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: vault-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Copy Certificate chart
      copy:
        src: files/global
        dest: /tmp/
      delegate_to: localhost

    - name: Copy certificate key
      copy:
        src: files/admin-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Copy Certificate file
      copy:
        src: files/voight.org.crt
        dest: /tmp/
      delegate_to: localhost

    - name: Add Voight.org Certificates
      command: >
        helm upgrade -i -n "{{ namespace }}" certificates /tmp/global
        --set namespace="{{ namespace }}"
        --set-file tls.crt=/tmp/voight.org.crt
        --set tls.key='{{ voightorgkey }}'
      delegate_to: localhost

    - name: Add Hashicorp Repo
      community.kubernetes.helm_repository:
        name: hashicorp
        repo_url: "https://helm.releases.hashicorp.com"
      delegate_to: localhost

    - name: Apply Vault
      command: helm upgrade -i -n "{{ namespace }}" vault hashicorp/vault -f /tmp/vault-values.yaml
      delegate_to: localhost

    - name: Initialize Vault
      command: echo "When the pod comes up, run:\nkubectl exec -it -n security vault-0 -- vault operator init"
