- name: Install Hashicorp Vault
  hosts: localhost
  connection: local
  vars_files:
    - files/admin-values.yaml
  vars:
    namespace: build

  tasks:
#    - name: Install Openshift Python Library
#      command: pip3 install openshift

    - name: Create security namespace
      kubernetes.core:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
        username: kubernetes-admin

    - name: Add Voight.org Certificates
      command: >
        helm upgrade -i -n "{{ namespace }}" certificates files/global
        --set namespace="{{ namespace }}"
        --set-file tls.crt=files/voight.org.crt
        --set tls.key='{{ voightorgkey }}'

    - name: Add Hashicorp Repo
      community.kubernetes.helm_repository:
        name: hashicorp
        repo_url: "https://helm.releases.hashicorp.com"

    - name: Apply Vault
      command: helm upgrade -i -n "{{ namespace }}" vault hashicorp/vault -f ./vault-values.yaml

    - name: Initialize Vault
      command: echo "When the pod comes up, run:\nkubectl exec -it -n security vault-0 -- vault operator init"
