- name: Install EKS
  hosts: localhost
  var:
    namespace: security

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create security namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: ../jenkins-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Add Hashicorp Repo
      community.kubernetes.helm_repository:
        name: hashicorp
        repo_url: "https://helm.releases.hashicorp.com"
      delegate_to: localhost

    - name: Apply Vault
      command: helm upgrade -n "{{ namespace }}" vault hashicorp/vault -f /tmp/vault-values.yaml
      delegate_to: localhost
